[package]
name = "render_text"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.12.7"
skia-safe = { version = "0.75" }
tokio = { version = "1.28", features = ["full"] }
